"""Pass Map - Streamlit page.

Two layers, and the UI keeps them visibly apart because they mean different
things. SCOPE picks the games and the passers, runs in SQL, and sets the
DENOMINATOR. FILTERS run in pandas and cut the numerator. The caption on the
chart states both, and it is generated by the same registry that built these
controls - so a filter cannot say one thing in the sidebar and another on the
chart.

Every control below is generated from shared.pass_filters.FILTERS. Adding a
filter there adds it here; there is no second list to keep in step.
"""
import math
import os
import sys
import tempfile

import streamlit as st
import matplotlib.pyplot as plt

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from shared.styles import BG_COLOR
from shared.motherduck import (
    get_teams_by_league, get_games_for_team, season_label, build_pass_map,
    season_competition, get_player_full_names,
)
from shared import pass_filters as pf
from mostly_finished_charts.pass_map_chart import create_pass_map, MAX_PLAYERS
from pages.streamlit_utils import custom_title_inputs

st.set_page_config(page_title="Pass Map", page_icon="🎯", layout="wide")
st.title("Pass Map")
st.caption("Every pass as a line, from where it started to where it ended. "
           "Scope sets the denominator; filters cut within it.")

# ── Scope: which games, whose passes ─────────────────────────────────────────

try:
    teams_by_league = get_teams_by_league()
except Exception as exc:
    st.error(f"Could not connect to database: {exc}")
    st.stop()

c1, c2, c3 = st.columns(3)
with c1:
    league = st.selectbox("League", options=[""] + list(teams_by_league))
with c2:
    if league:
        options = teams_by_league[league]
        name = st.selectbox("Team", options=[""] + [t['display_name'] for t in options])
        team = next((t for t in options if t['display_name'] == name), None)
    else:
        st.selectbox("Team", options=[], disabled=True)
        team = None
with c3:
    mode = st.selectbox("Scope", options=["Single match", "Season", "Last N matches"],
                        disabled=not team)

if not team:
    st.info("Pick a league and a team to begin.")
    st.stop()

games = get_games_for_team(team['team_id'])
if not games:
    st.warning("No games found for this team.")
    st.stop()

seasons = {g['season_id']: season_label(g['season_id'], g.get('season_name'))
           for g in games if g.get('season_id')}
s1, s2 = st.columns([2, 3])
with s1:
    season_id = None
    if seasons:
        picked = st.selectbox("Season / competition", options=list(seasons.values()))
        season_id = next(k for k, v in seasons.items() if v == picked)
in_season = [g for g in games if g.get('season_id') == season_id] if season_id else games

if mode == "Single match":
    with s2:
        label = st.selectbox("Match", options=[""] + [g['label'] for g in in_season])
    picked_games = [g for g in in_season if g['label'] == label]
elif mode == "Last N matches":
    with s2:
        n_last = st.slider("How many of the most recent matches", 1,
                           max(len(in_season), 1), min(5, len(in_season)))
    picked_games = in_season[:n_last]
else:
    picked_games = in_season

if not picked_games:
    st.info("Pick a match.")
    st.stop()

against = st.toggle(
    "Passes conceded (the opponents' passes in these games)", value=False,
    help="Same games, the other side of the ball. Not mirrored - both views "
         "stay in the same frame so they can be compared.")

with st.spinner("Loading passes..."):
    population, info, team_color = build_pass_map(
        tuple(g['game_id'] for g in picked_games), team['team_id'], against)

if population.empty:
    st.warning("No passes found for that scope.")
    st.stop()
population = pf.annotate_passes(population)

# ── Passers: the player mode, one code path rather than two ──────────────────

names = sorted({p for p in population['passer'].dropna().unique()})
players = st.multiselect(
    "Passers (leave empty for the whole team)", options=names,
    help=f"Up to {MAX_PLAYERS}. Colour means player identity on this chart, and "
         f"a fourth colour cannot be told apart from the other three.")
if len(players) > MAX_PLAYERS:
    st.error(
        f"{MAX_PLAYERS} passers is the limit, and it is a measurement rather "
        f"than a preference. Any two players' lines can cross anywhere on the "
        f"pitch, so every pair has to separate on colour alone - line style is "
        f"already spent on completion and a 1px line cannot carry texture. The "
        f"best available fourth colour sits below the threshold where most "
        f"people can reliably tell it from the third. Drop one.")
    st.stop()
if players:
    population = population[population['passer'].isin(players)]
    if population.empty:
        st.warning("No passes by those players in this scope.")
        st.stop()

# ── Filters: the numerator ───────────────────────────────────────────────────

st.sidebar.header("Filters")
match_all = st.sidebar.radio(
    "Combine filters with", ["Match all", "Match any"], horizontal=True,
    help="Within one filter the choices are always OR - a pass cannot start in "
         "two thirds at once. This joins the filters to each other.",
) == "Match all"

selections = {}
for group in pf.GROUPS:
    members = [f for f in pf.FILTERS if f.group == group]
    with st.sidebar.expander(group, expanded=(group == pf.OUTCOME)):
        for f in members:
            key = f"pm_{f.id}"
            if f.kind == 'flag':
                val = st.checkbox(f.label, key=key, help=f.note)
                selections[f.id] = val
            elif f.kind == 'multi':
                try:
                    present = set(f.resolver(population).dropna().unique())
                except Exception:
                    present = set()
                # Offer only what this population can actually answer. Pressure
                # is the case that matters: seven competitions never record it,
                # and a filter that looks available but returns nothing reads as
                # "this team never passes under pressure" rather than "we do not
                # have this measurement here".
                opts = [o for o in f.options if o in present] or sorted(present)
                if not opts:
                    st.caption(f"{f.label} - not available for this selection")
                    continue
                selections[f.id] = st.multiselect(f.label, options=opts,
                                                  key=key, help=f.note)
            else:
                col = f.resolver
                hi = float(population[col].max()) if col in population else 0.0
                # Two ways this used to take the page down, both reachable by
                # picking one passer. An all-NaN column returns NaN from max(),
                # and `NaN <= 0` is False, so it walked straight past the
                # guard; and a real but tiny maximum - one pass with xA 0.004 -
                # ROUNDED to 0.0, so min and max were both 0.0.
                if not math.isfinite(hi) or hi <= 0:
                    continue
                step = 0.01 if hi <= 1.5 else 1.0
                # Round the ceiling UP to a whole step, never down: the top of
                # the slider has to be reachable, or the chart's own maximum
                # sits outside the control that selects it.
                top = round(math.ceil(hi / step) * step, 2)
                if top <= 0:
                    continue
                selections[f.id] = st.slider(f.label, 0.0, top, 0.0,
                                             step=step, key=key, help=f.note)

shown, phrases = pf.apply_filters(population, selections, match_all)
# Two renderings of the same cut. `caption` is the full sentence with the
# ratio, used for the no-results warning below; `filter_text` is the qualifier
# list alone, which is what the chart's header wants - the counts are already
# the biggest number in its panel.
caption = pf.caption(len(shown), len(population), phrases, match_all)
# Receivers are IDENTITY, so the chart puts them in the title alongside the
# passers - which means the filter line must not also say "completed to X".
receivers = list(selections.get('receiver') or [])
# Full names for the title only. The frame keys on the feed's short form
# ("I. Konaté") everywhere else - the colour map, the leaders table - so this
# is a display lookup, resolved by playerId for the handful of players named.
_ids = {}
for col, idcol in (('passer', 'passerId'), ('receiver', 'receiverId')):
    if col in population and idcol in population:
        pairs = population[[col, idcol]].dropna().drop_duplicates()
        _ids.update(dict(zip(pairs[col], pairs[idcol])))
_wanted = [n for n in list(players) + receivers if n in _ids]
_full = get_player_full_names(tuple(_ids[n] for n in _wanted))
player_labels = {n: _full[_ids[n]] for n in _wanted if _ids[n] in _full}
filter_text = pf.filter_phrase(phrases, match_all,
                               skip=('receiver',) if receivers else ())

st.sidebar.header("Chart")
# The SEASON's competition, not the team's league bucket. Aston Villa's league
# bucket is the Premier League, so a Champions League tie was labelled with
# both - the bucket says where a club plays domestically, not what this match
# was. See split_season_label.
competition = st.sidebar.text_input(
    "Competition name", value=season_competition([season_id]) or league or "")
title, subtitle = custom_title_inputs(
    "pass_map", (info.get('team_name') or '').upper(),
    "")

# ── Render ───────────────────────────────────────────────────────────────────

if shown.empty:
    st.warning(f"No passes match those filters. {caption}")
    st.stop()

fig = create_pass_map(shown, info, team_color, n_population=len(population),
                      caption_text=caption, filter_text=filter_text,
                      players=players, receivers=receivers,
                      player_labels=player_labels, competition=competition,
                      custom_title=title, custom_subtitle=subtitle)
st.pyplot(fig, use_container_width=True)

path = os.path.join(tempfile.gettempdir(), "pass_map.png")
fig.savefig(path, dpi=300, facecolor=BG_COLOR, edgecolor='none')
with open(path, 'rb') as fh:
    st.download_button("Download PNG (300 dpi)", fh, "pass_map.png", "image/png")
plt.close(fig)
